In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [7]:
col_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'Price']

In [14]:
house_df = pd.read_csv("house Prediction Data Set.csv", sep=r'\s+', header=None, names=col_names)
house_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [5]:
print("Columns inthe dataset:", house_df.columns.tolist()

Columns inthe dataset: [' 0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00']

In [15]:
house_df = house_df.dropna()

X_house = house_df.drop('Price', axis=1)
y_house = house_df['Price']

X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(X_house, y_house, test_size=0.2, random_state=42)

lr_model = LinearRegression()
lr_model.fit(X_train_h, y_train_h)

predictions = lr_model.predict(X_test_h)
mse = mean_squared_error(y_test_h, predictions)
r2 = r2_score(y_test_h, predictions)

print("--- Model Evaluation ---")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared: {r2:.4f}")

print("\n--- Model Coefficients ---")
coefficients = pd.DataFrame({'Feature': X_house.columns, 'Coefficient': lr_model.coef_})
coefficients['Abs_Coefficient'] = coefficients['Coefficient'].abs()
coefficients = coefficients.sort_values(by='Abs_Coefficient', ascending=False).drop('Abs_Coefficient', axis=1)

display(coefficients.head())

--- Model Evaluation ---
Mean Squared Error (MSE): 24.29
R-squared: 0.6688

--- Model Coefficients ---

    Feature  Coefficient
4       NOX   -17.202633
5        RM     4.438835
3      CHAS     2.784438
7       DIS    -1.447865
10  PTRATIO    -0.915456