In [15]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("churn-bigml-20.csv")
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [5]:
missing_data = df.isnull().sum()
print("Missing values per column \n", missing_data[missing_data > 0])

Missing values per column
 Series([], dtype: int64)

In [11]:
df.shape

(667, 20)

In [10]:
print("\nData types overview : \n", df.dtypes.value_counts())

Data types overview :
 int64      8
float64    8
str        3
bool       1
Name: count, dtype: int64

In [14]:
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns.tolist()
print("Categorical columns found", categorical_cols)

le = LabelEncoder()

if 'Churn' in categorical_cols:
    df['Churn'] = le.fit_transform(df['Churn'])
    
    categorical_cols.remove('Churn') 
    print("\n'Churn' successfully label encoded (0 = False, 1 = True).")

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print("\nNew dataset shape after encoding:", df_encoded.shape)
display(df_encoded.head())

Categorical columns found ['State', 'International plan', 'Voice mail plan', 'Churn']

'Churn' successfully label encoded (0 = False, 1 = True).

New dataset shape after encoding: (667, 69)

/tmp/ipykernel_291999/4242807650.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object', 'bool']).columns.tolist()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,...,State_TX,State_UT,State_VA,State_VT,State_WA,State_WI,State_WV,State_WY,International plan_Yes,Voice mail plan_Yes
0,117,408,0,184.5,97,31.37,351.6,80,29.89,215.8,...,False,False,False,False,False,False,False,False,False,False
1,65,415,0,129.1,137,21.95,228.5,83,19.42,208.8,...,False,False,False,False,False,False,False,False,False,False
2,161,415,0,332.9,67,56.59,317.8,97,27.01,160.6,...,False,False,False,False,False,False,False,False,False,False
3,111,415,0,110.4,103,18.77,137.3,102,11.67,189.6,...,False,False,False,False,False,False,False,False,False,False
4,49,510,0,119.3,117,20.28,215.1,109,18.28,178.7,...,False,False,False,False,False,False,False,False,False,False

In [16]:
X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()


scaler = StandardScaler()

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

print("Data successfully split and scaled!")
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
display(X_train[numerical_cols].head())

Data successfully split and scaled!
Training features shape: (533, 68)
Testing features shape: (134, 68)

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
234,-1.179904,1.738958,-0.595854,0.150424,-0.060953,0.150366,-1.708028,-0.069068,-1.708638,1.020930,-0.663028,1.018689,2.480249,0.589579,2.483071,-1.164896
398,-0.080576,-0.684404,-0.595854,-1.972756,-0.354521,-1.972374,0.228910,0.088029,0.229869,0.671305,1.235865,0.672934,-0.267534,-1.419663,-0.261648,3.285924
278,-0.911179,-0.684404,-0.595854,-1.670984,-1.235225,-1.671238,1.154491,0.559321,1.154532,-0.262375,1.235865,-0.261054,-0.375999,0.187730,-0.382148,-0.423092
61,0.432443,-0.684404,-0.595854,-0.183680,0.330470,-0.183524,2.919878,-1.692405,2.919372,2.009175,-0.663028,2.011050,0.347102,-0.615966,0.340851,-1.164896
145,1.776066,-0.518095,-0.595854,0.764745,-1.235225,0.764260,0.204973,1.606635,0.204054,-0.872703,-1.012824,-0.871738,-0.050603,-1.017815,-0.047426,1.060514